apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-elector-nodejs
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: leader-elector
    spec:
      containers:
      - image: xwangqingyuan/elector-client-nodejs
        imagePullPolicy: IfNotPresent
        name: nodejs
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
      - image: xwangqingyuan/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: elector
        args:
          - --election=elect-master
          - --http=localhost:4040
        ports:
        - containerPort: 4040
          protocol: TCP
        resources:
          requests:
            cpu: 100m
