apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: elector-sidecar
spec:
  containers:
  - image: xwangqingyuan/elector-client-nodejs
    imagePullPolicy: IfNotPresent
    name: nodejs
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        cpu: 100m
  - image: xwangqingyuan/leader-elector:0.4
    imagePullPolicy: IfNotPresent
    name: elector
    args:
      - --election=example
      - --http=localhost:4040
    ports:
    - containerPort: 4040
      protocol: TCP
    resources:
      requests:
        cpu: 100m
